services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    depends_on:
      - postgres
    container_name: server
    working_dir: /app
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    environment:
      - TZ=America/Sao_Paulo  # Adicione a variável de timezone

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env
    environment:
      - TZ=America/Sao_Paulo  # Adicione a variável de timezone
 
volumes:
  progresDB:
  redisDB:
