version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    depends_on:
      - postgres
    container_name: server
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/node/app

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env

 
volumes:
  progresDB:
  redisDB:

